version: '3.8'

services:
  harlequin-sidecar:
    build: .
    container_name: harlequin-sidecar
    ports:
      - "${PORT:-3001}:3001"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./.env:/app/.env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3001
    restart: unless-stopped
    networks:
      - harlequin-network
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3001/health').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: harlequin-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - harlequin-sidecar
    networks:
      - harlequin-network
    profiles:
      - production

networks:
  harlequin-network:
    driver: bridge
